version: '3.1'

services:
  minecraft:
    image: baronmc/minecraft-server:${MINCRAFT_VERSION}
    container_name: spigot
    restart: always
    volumes:
     - "${SERVER_DIR}:/server/"
    ports:
     - "25565:25565"